import { useEffect, useId, useRef, useState, type ReactNode } from "react";
import { useSearchParams } from "react-router-dom";
import { adminErrorKey } from "../lib/adminApi";
import { useAdminCopy, type AdminCopyKey } from "../lib/adminCopy";
import { useLocale } from "../providers/LocaleProvider";
import { Icon, type IconName } from "./Icon";
import { WorkspaceSelect } from "./WorkspaceSelect";

export function AdminButton({ label, icon, danger, disabled, onClick }: { label: string; icon: IconName; danger?: boolean; disabled?: boolean; onClick: () => void }) {
  return <button className={`table-action${danger ? " admin-danger" : ""}`} type="button" disabled={disabled} aria-label={label} title={label} onClick={onClick}><Icon name={icon} size={18}/></button>;
}
export function AdminPanel({ section, loading, error, reload, children }: { section: "overview" | "users" | "scheduling" | "quotas" | "operations" | "audit"; loading: boolean; error: unknown; reload: () => void; children: ReactNode }) {
  const t = useAdminCopy();
  return <section className="admin-page"><header className="admin-page-header"><div><h1>{t(section)}</h1><p>{t(`${section}Body` as AdminCopyKey)}</p></div><AdminButton label={t("refresh")} icon="refresh" onClick={reload} disabled={loading}/></header>
    {loading ? <div className="admin-state" role="status"><Icon name="refresh" size={28} spin/><p>{t("loading")}</p></div> : error ? <div className="admin-state" role="alert"><Icon name="alert" size={28}/><h2>{t("loadFailed")}</h2><p>{t(adminErrorKey(error))}</p><button className="button button-outline" type="button" onClick={reload}>{t("retry")}</button></div> : children}
  </section>;
}
export function AdminEmpty({ clear }: { clear?: () => void }) { const t = useAdminCopy(); return <div className="admin-state"><Icon name="layers" size={28}/><h2>{t("empty")}</h2><p>{t("emptyBody")}</p>{clear && <button className="button button-outline" type="button" onClick={clear}>{t("clearFilters")}</button>}</div>; }
export function AdminTable({ label, headings, children }: { label: string; headings: string[]; children: ReactNode }) { return <div className="admin-table-wrap" role="region" aria-label={label} tabIndex={0}><table className="admin-table"><thead><tr>{headings.map((heading, index) => <th key={index} scope="col">{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
export function AdminPager({ page, size, total, onChange }: { page: number; size: number; total: number; onChange: (page: number, size: number) => void }) { const t = useAdminCopy(); const pages = Math.max(1, Math.ceil(total / size)); return <nav className="admin-pagination" aria-label={t("page")}><span>{t("total")} {total}</span><WorkspaceSelect aria-label={t("rows")} value={size} onChange={event => onChange(1, Number(event.target.value))}>{[20, 50, 100].map(size => <option key={size} value={size}>{size}</option>)}</WorkspaceSelect><div className="admin-actions"><AdminButton label={t("previous")} icon="chevronLeft" disabled={page <= 1} onClick={() => onChange(page - 1, size)}/><span>{page} / {pages}</span><AdminButton label={t("next")} icon="chevronRight" disabled={page >= pages} onClick={() => onChange(page + 1, size)}/></div></nav>; }
export function useAdminQuery() { const [params, setParams] = useSearchParams(); const rawPage = Number(params.get("page") || 1); const page = Number.isSafeInteger(rawPage) && rawPage > 0 ? rawPage : 1; const rawSize = Number(params.get("page_size") || 20); const size = [20, 50, 100].includes(rawSize) ? rawSize : 20; return { params, page, size, update: (values: Record<string, string | number>) => { const next = new URLSearchParams(params); for (const [key, value] of Object.entries(values)) { if (value === "") next.delete(key); else next.set(key, String(value)); } setParams(next); } }; }
export function AdminFilters({ search, values, options, onApply }: { search?: string; values: Record<string, string>; options: { key: string; label: string; values: { value: string; label: string }[] }[]; onApply: (values: Record<string, string>) => void }) {
  const t = useAdminCopy(); const id = useId(); const [open, setOpen] = useState(false); const [draft, setDraft] = useState(values); const [query, setQuery] = useState(search || ""); const root = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null);
  useEffect(() => { setDraft(values); setQuery(search || ""); }, [JSON.stringify(values), search]);
  useEffect(() => { if (!open) return; root.current?.querySelector("select")?.focus(); const close = (event: PointerEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; window.addEventListener("pointerdown", close); return () => window.removeEventListener("pointerdown", close); }, [open]);
  return <form className="task-filters admin-filters" onSubmit={event => { event.preventDefault(); onApply({ ...draft, ...(search !== undefined ? { q: query.trim() } : {}) }); setOpen(false); trigger.current?.focus(); }}>
    {search !== undefined && <label className="admin-search"><Icon name="search" size={18}/><input type="search" aria-label={t("search")} value={query} maxLength={100} onChange={event => setQuery(event.target.value)} placeholder={t("search")}/><button type="submit" className="table-action" aria-label={t("search")} title={t("search")}><Icon name="arrow" size={18}/></button></label>}
    <div className="task-filter-control" ref={root} onBlur={event => { if (!event.currentTarget.contains(event.relatedTarget)) setOpen(false); }} onKeyDown={event => { if (event.key === "Escape") { setOpen(false); trigger.current?.focus(); } }}><button ref={trigger} className={`button button-quiet${Object.values(values).some(Boolean) ? " has-filters" : ""}`} type="button" aria-expanded={open} aria-controls={id} onClick={() => setOpen(value => !value)}><Icon name="filter"/>{t("filter")}</button>{open && <div id={id} className="task-filter-popover">{options.map(option => <label key={option.key}><span>{option.label}</span><WorkspaceSelect value={draft[option.key] || ""} onChange={event => setDraft(current => ({ ...current, [option.key]: event.target.value }))}><option value="">{t("all")}</option>{option.values.map(value => <option key={value.value} value={value.value}>{value.label}</option>)}</WorkspaceSelect></label>)}<div className="task-filter-actions"><button className="button button-quiet" type="button" onClick={() => { const empty = Object.fromEntries(Object.keys(draft).map(key => [key, ""])); setDraft(empty); setQuery(""); onApply({ ...empty, ...(search !== undefined ? { q: "" } : {}) }); setOpen(false); trigger.current?.focus(); }}>{t("clearFilters")}</button><button className="button button-primary" type="submit">{t("apply")}</button></div></div>}</div>
  </form>;
}
const statusKeys: Record<string, AdminCopyKey> = { queued: "queued", running: "running", failed: "failed", completed: "completed", canceled: "canceled", expired: "expired", draft: "draft", uploading: "uploading", interrupted: "interrupted" };
export function AdminStatus({ status }: { status: string }) { const t = useAdminCopy(); return <span className={`admin-status${["failed", "interrupted"].includes(status) ? " is-warning" : ""}`}><Icon name={status === "completed" ? "check" : ["failed", "interrupted"].includes(status) ? "alert" : "clock"} size={16}/>{statusKeys[status] ? t(statusKeys[status]) : status}</span>; }
export function useAdminFormat() { const { locale } = useLocale(); const t = useAdminCopy(); return { number: (value: number | null | undefined) => value == null ? t("unknown") : new Intl.NumberFormat(locale).format(value), date: (value: string | null | undefined) => { const date = new Date(value || ""); return Number.isNaN(date.valueOf()) ? t("unknown") : new Intl.DateTimeFormat(locale === "zh" ? "zh-CN" : "en", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date); }, bytes: (value: number) => `${new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(value / 1024 ** 3)} GiB` }; }
