export const workspaceCopy = {
  zh: {
    workspaceNav: "工作台导航", createTask: "创建任务", tasks: "任务列表", recent: "最近任务", settings: "设置",
    account: "账户", menuOpen: "打开工作台菜单", menuClose: "关闭工作台菜单", github: "GitHub", api: "API",
    newTitle: "创建分析任务", newBody: "上传注册视频与四路机位视频。每一路独立验证，全部完成后再提交后台队列。",
    taskTitle: "任务标题", defaultTitle: "未命名训练", titleRequired: "请输入任务标题", titleTooLong: "任务标题不能超过 120 个字符", mode: "分析模式", quick: "快速", full: "完整", uploadHint: "点击或拖放视频到这里",
    submit: "提交分析", submitting: "正在提交…", replace: "替换", retry: "重试", uploaded: "已验证", uploadFailed: "上传失败",
    presetHeading: "从示例开始", presetBody: "浏览四个真实示例结果，或直接用相同素材创建新任务。", viewPreset: "查看示例",
    listTitle: "任务列表", listBody: "搜索、筛选并管理属于你的分析任务。", search: "搜索任务", status: "状态", allStatuses: "全部状态", allModes: "全部模式", filter: "筛选",
    previous: "上一页", next: "下一页", emptyTasks: "没有符合条件的任务", created: "创建时间", progress: "进度", actions: "操作", open: "打开",
    cancel: "取消", delete: "删除", retryTask: "重试", confirmCancel: "取消任务", confirmRetry: "重试任务", confirmDelete: "删除任务", confirm: "确认", dismiss: "返回",
    detailLoading: "正在加载任务", detailError: "无法加载任务", resultLoading: "正在加载结果", resultUnavailable: "结果暂时不可用", tryAgain: "重试",
    phases: "阶段合成", cam1: "机位 1", cam2: "机位 2", cam3: "机位 3", cam4: "机位 4", mediaUnavailable: "此视角没有可播放媒体", mediaViews: "媒体视角", resultViews: "结果视图",
    summary: "概览", timeline: "时间线", json: "JSON", attempts: "出手", makes: "命中", participants: "参与者", actionsCount: "动作", downloadJson: "下载 JSON 结果",
    draftBody: "任务尚未提交，可继续补充或替换视频。", uploadingBody: "正在验证上传的视频，请等待当前文件完成。", queuedBody: "任务已进入后台队列，可以离开页面后稍后回来。", runningBody: "正在分析视频，进度会自动更新。", failedBody: "任务未完成，请查看错误后重试。", canceledBody: "任务已取消，可以从任务列表重新运行。", expiredBody: "草稿已过期，请创建新任务。", emptyResult: "任务完成，但当前没有可展示的结果。",
    usePreset: "用此示例创建任务", creatingPreset: "正在创建…",
    settingsBody: "查看当前配额、数据保留规则与界面偏好。", usage: "用量与配额", retention: "数据保留", preferences: "界面偏好", language: "语言", theme: "主题",
    submittedToday: "今日提交", unfinished: "未完成任务", drafts: "草稿", apiKeys: "有效 API 密钥", enrollment: "注册数据", rawInputs: "原始输入", results: "结果",
    loadFailed: "暂时无法加载数据", noRecent: "暂无最近任务",
  },
  en: {
    workspaceNav: "Workspace navigation", createTask: "Create task", tasks: "Tasks", recent: "Recent tasks", settings: "Settings",
    account: "Account", menuOpen: "Open workspace menu", menuClose: "Close workspace menu", github: "GitHub", api: "API",
    newTitle: "Create analysis task", newBody: "Upload one enrollment video and four camera views. Each is verified independently before submission.",
    taskTitle: "Task title", defaultTitle: "Untitled session", titleRequired: "Enter a task title", titleTooLong: "Task title cannot exceed 120 characters", mode: "Analysis mode", quick: "Quick", full: "Full", uploadHint: "Click or drop a video here",
    submit: "Submit analysis", submitting: "Submitting…", replace: "Replace", retry: "Retry", uploaded: "Verified", uploadFailed: "Upload failed",
    presetHeading: "Start from an example", presetBody: "Explore all four real example results or run one as a new task.", viewPreset: "View example",
    listTitle: "Tasks", listBody: "Search, filter, and manage your analysis tasks.", search: "Search tasks", status: "Status", allStatuses: "All statuses", allModes: "All modes", filter: "Filter",
    previous: "Previous", next: "Next", emptyTasks: "No matching tasks", created: "Created", progress: "Progress", actions: "Actions", open: "Open",
    cancel: "Cancel", delete: "Delete", retryTask: "Retry", confirmCancel: "Cancel task", confirmRetry: "Retry task", confirmDelete: "Delete task", confirm: "Confirm", dismiss: "Back",
    detailLoading: "Loading task", detailError: "Could not load task", resultLoading: "Loading result", resultUnavailable: "Result is temporarily unavailable", tryAgain: "Retry",
    phases: "Phase mosaic", cam1: "Camera 1", cam2: "Camera 2", cam3: "Camera 3", cam4: "Camera 4", mediaUnavailable: "No playable media for this view", mediaViews: "Media views", resultViews: "Result views",
    summary: "Summary", timeline: "Timeline", json: "JSON", attempts: "Attempts", makes: "Makes", participants: "Participants", actionsCount: "Actions", downloadJson: "Download JSON result",
    draftBody: "This draft has not been submitted. You can add or replace videos.", uploadingBody: "A video upload is being validated. Wait for it to finish.", queuedBody: "This task is queued in the background. You can leave and return later.", runningBody: "Video analysis is in progress and updates automatically.", failedBody: "The task did not finish. Review the error and retry.", canceledBody: "This task was canceled. You can run it again from the task list.", expiredBody: "This draft expired. Create a new task.", emptyResult: "The task completed without a displayable result.",
    usePreset: "Create task from this example", creatingPreset: "Creating…",
    settingsBody: "Review quotas, retention rules, and interface preferences.", usage: "Usage and quotas", retention: "Data retention", preferences: "Interface preferences", language: "Language", theme: "Theme",
    submittedToday: "Submitted today", unfinished: "Unfinished tasks", drafts: "Drafts", apiKeys: "Active API keys", enrollment: "Enrollment data", rawInputs: "Raw inputs", results: "Results",
    loadFailed: "Could not load data", noRecent: "No recent tasks",
  },
} as const;

export type WorkspaceCopyKey = keyof typeof workspaceCopy.zh;
