export const copy = {
  zh: {
    menuOpen: "打开导航菜单", menuClose: "关闭导航菜单",
    home: "首页", api: "API", github: "GitHub", onlineUse: "在线使用", login: "登录", register: "注册", account: "账户",
    mainNav: "主导航", brandHome: "大山冰首页", brandMark: "大山冰标志", brandPrimary: "大山冰", brandSecondary: "DaShanBing",
    metaTitle: "大山冰 · 多机位篮球训练复盘", metaDescription: "好球还是好巧？上传篮球训练录像，从不同机位重看动作、出手和命中。",
    themeLight: "切换到浅色主题", themeDark: "切换到深色主题", language: "English",
    heroEyebrow: "球场嘴硬终结者", heroTitle: "让我看看你打球什么b样",
    heroBody: "是丝滑跳投，还是原地打铁？把录像交出来，换个角度看看自己。",
    heroPrimary: "上传，验验货", heroSecondary: "先看看别人的", queueLabel: "后台队列", queueTitle: "提交后安心离开",
    queueBody: "上传并提交后，关掉页面也能继续处理。回来就能查看进度和结果。",
    previewTitle: "快速演示 · 跳投复盘", previewStatus: "已完成", previewSummary: "训练概览", previewActions: "动作时间线",
    previewModelAlt: "实际模型输出：四机位篮球画面、人物骨架、球框与跳投阶段标注", previewPoseAlt: "真实模型处理画面：跳投出手时的人物骨架与篮球、篮筐检测", previewPoseCaption: "跳投 · 出手阶段", previewMixedAlt: "混合动作示例的实际四机位模型处理画面",
    previewAttempts: "出手", previewMakes: "命中", previewPeople: "参与者",
    capabilitiesEyebrow: "录像面前，人人平等", capabilitiesTitle: "你以为的自己，和录像里的自己",
    capabilityOneTitle: "这个角度帅，换一个呢？", capabilityOneBody: "四个机位一起看，帅气和尴尬都别漏。交上注册视频和四路录像，沿着时间线重看那一球。",
    capabilityTwoTitle: "好球还是好巧？回放见。", capabilityTwoBody: "起跳、出手、球往哪儿飞，拆开慢慢看。动作识别和球轨各有结果，拿不准的地方就回到原片。",
    capabilityThreeTitle: "你继续打，录像我来翻。", capabilityThreeBody: "视频交齐就去打下一场。分析在后台排队，你不用对着进度条练防守。",
    examplesEyebrow: "先围观，再上场", examplesTitle: "来，看看这几球怎么打的", examplesBody: "有进球，也有打铁。原片、动作和分析结果都在，自己看。",
    quickTitle: "快速演示", quickBody: "4 次出手，进了 2 个。剩下那 2 球怎么回事？点开回放看看。", mixedTitle: "混合动作",
    mixedBody: "15 次三威胁，12 次跳投。晃得够不够帅，出手稳不稳，换个机位看看。", quickTag: "QUICK", mixedTag: "FULL", viewExample: "查看示例",
    ctaTitle: "别光说你那球有多帅。", ctaBody: "传上来。进球可以回味，打铁也得认。", ctaAction: "传上来看看",
    footerLine: "大山冰 · 多机位篮球训练复盘", footerNote: "AI 也有看走眼的时候，拿不准就看原片。",
    authLoginTitle: "登录大山冰", authLoginBody: "继续查看你的训练任务、排队进度与复盘结果。",
    authRegisterTitle: "创建大山冰账号", authRegisterBody: "注册后即可提交训练视频，并在任意时间回来继续。",
    identity: "用户名或邮箱", username: "用户名", email: "邮箱", password: "密码", identityPlaceholder: "coach 或 coach@example.com",
    usernamePlaceholder: "3–50 个字符", emailPlaceholder: "coach@example.com", passwordPlaceholder: "至少 8 个字符",
    submitLogin: "登录", submitRegister: "创建账号", submittingLogin: "正在登录…", submittingRegister: "正在创建…",
    noAccount: "还没有账号？", hasAccount: "已经有账号？", goRegister: "立即注册", goLogin: "返回登录",
    identityRequired: "请输入用户名或邮箱", usernameShort: "用户名至少需要 3 个字符", emailInvalid: "请输入有效的邮箱地址",
    passwordShort: "密码至少需要 8 个字符", invalidCredentials: "用户名、邮箱或密码不正确", duplicateIdentity: "该用户名或邮箱已被注册",
    usernameRequired: "请输入用户名", usernameLong: "用户名不能超过 50 个字符", emailRequired: "请输入邮箱", emailLong: "邮箱不能超过 255 个字符",
    passwordRequired: "请输入密码", passwordLong: "密码不能超过 128 个字符", requestFailed: "暂时无法完成请求，请稍后重试",
    authChecking: "正在确认登录状态", authCheckFailed: "暂时无法确认登录状态", authCheckFailedBody: "网络或服务出现问题。请重试，我们不会把这次错误当作退出登录。", retry: "重试",
  },
  en: {
    menuOpen: "Open navigation menu", menuClose: "Close navigation menu",
    home: "Home", api: "API", github: "GitHub", onlineUse: "Online Use", login: "Log in", register: "Sign up", account: "Account",
    mainNav: "Main navigation", brandHome: "DaShanBing home", brandMark: "DaShanBing logo", brandPrimary: "DaShanBing", brandSecondary: "大山冰",
    metaTitle: "DaShanBing · Multi-camera basketball review", metaDescription: "Great shot or lucky bounce? Review your basketball footage from every angle, with actions, shots and results side by side.",
    themeLight: "Switch to light theme", themeDark: "Switch to dark theme", language: "中文",
    heroEyebrow: "The tape settles it", heroTitle: "Talk is cheap. Show me your game.",
    heroBody: "Silky jumper or another brick? Drop the footage. See what your game looks like from the other side.",
    heroPrimary: "Put my game on tape", heroSecondary: "Scout the demos", queueLabel: "Background queue", queueTitle: "Submit, then step away",
    queueBody: "Once uploaded and submitted, your task keeps running with the page closed. Come back for progress and results.",
    previewTitle: "Quick demo · Jump shots", previewStatus: "Completed", previewSummary: "Session overview", previewActions: "Action timeline",
    previewModelAlt: "Actual model output: four basketball camera views, pose skeletons, ball boxes and shot phases", previewPoseAlt: "Actual shot-release output with pose, basketball and hoop detections", previewPoseCaption: "Jump shot · Release", previewMixedAlt: "Actual four-camera model output from the mixed-actions example",
    previewAttempts: "Attempts", previewMakes: "Makes", previewPeople: "Players",
    capabilitiesEyebrow: "The camera has no favorites", capabilitiesTitle: "The player in your head. The player on tape.",
    capabilityOneTitle: "Nice from here. How about over there?", capabilityOneBody: "Four angles catch the highlights and the humbling bits. Submit enrollment footage and four camera views, then revisit each play on the timeline.",
    capabilityTwoTitle: "Great shot or lucky bounce?", capabilityTwoBody: "Break down the jump, the release and the flight. Actions and ball tracks have separate results. When in doubt, check the original footage.",
    capabilityThreeTitle: "You keep hooping. We’ll roll the tape.", capabilityThreeBody: "Send the videos and get back on court. Analysis runs in the background. No need to play defense on a progress bar.",
    examplesEyebrow: "Watch first. Your turn next.", examplesTitle: "Let’s see how these plays went", examplesBody: "Makes and misses included. Check the original footage, detected actions and results for yourself.",
    quickTitle: "Quick demo", quickBody: "Four attempts. Two makes. What happened to the other two? Roll the tape.", mixedTitle: "Mixed actions",
    mixedBody: "15 triple threats. 12 jump shots. Sell the fake? Stick the landing? Try another angle.", quickTag: "QUICK", mixedTag: "FULL", viewExample: "View example",
    ctaTitle: "Still talking about that one shot?", ctaBody: "Show us. Relive the buckets. Own the bricks.", ctaAction: "Show my game",
    footerLine: "DaShanBing · Multi-camera basketball review", footerNote: "AI can misread a play too. When in doubt, check the tape.",
    authLoginTitle: "Log in to DaShanBing", authLoginBody: "Continue to your training tasks, queue progress, and review results.",
    authRegisterTitle: "Create a DaShanBing account", authRegisterBody: "Submit training video, then return whenever the review is ready.",
    identity: "Username or email", username: "Username", email: "Email", password: "Password", identityPlaceholder: "coach or coach@example.com",
    usernamePlaceholder: "3–50 characters", emailPlaceholder: "coach@example.com", passwordPlaceholder: "At least 8 characters",
    submitLogin: "Log in", submitRegister: "Create account", submittingLogin: "Logging in…", submittingRegister: "Creating account…",
    noAccount: "New to DaShanBing?", hasAccount: "Already have an account?", goRegister: "Create one", goLogin: "Back to login",
    identityRequired: "Enter your username or email", usernameShort: "Username must be at least 3 characters", emailInvalid: "Enter a valid email address",
    passwordShort: "Password must be at least 8 characters", invalidCredentials: "The username, email, or password is incorrect",
    duplicateIdentity: "That username or email is already registered", usernameRequired: "Enter a username", usernameLong: "Username cannot exceed 50 characters",
    emailRequired: "Enter an email address", emailLong: "Email cannot exceed 255 characters", passwordRequired: "Enter a password", passwordLong: "Password cannot exceed 128 characters",
    requestFailed: "We could not complete the request. Try again shortly.", authChecking: "Checking your sign-in status",
    authCheckFailed: "We could not confirm your sign-in status", authCheckFailedBody: "There may be a network or service problem. Retry without being signed out.", retry: "Retry",
  },
} as const;

export type Locale = keyof typeof copy;
export type CopyKey = keyof (typeof copy)["zh"];
