export const copy = {
  zh: {
    logout: "退出登录", loggingOut: "正在退出", logoutFailed: "退出失败，请稍后重试",
    menuOpen: "打开导航菜单", menuClose: "关闭导航菜单",
    home: "首页", api: "API", github: "GitHub", onlineUse: "在线使用", login: "登录", register: "注册", account: "账户",
    mainNav: "主导航", brandHome: "大山冰首页", brandMark: "大山冰标志", brandPrimary: "大山冰", brandSecondary: "DaShanBing",
    metaTitle: "大山冰 · 多机位篮球训练复盘", metaDescription: "大山冰将多路篮球训练视频转化为可复盘的动作与投篮洞察",
    themeLight: "切换到浅色主题", themeDark: "切换到深色主题", language: "English",
    heroEyebrow: "多机位篮球训练复盘", heroTitle: "让我看看你打球什么b样",
    heroBody: "五路视频，一次提交，后台完成分析，稍后回来查看进度与复盘结果",
    heroPrimary: "开始一次复盘", heroSecondary: "查看演示", queueLabel: "后台队列", queueTitle: "提交后安心离开",
    queueBody: "任务状态会被保留，回来时从上次进度继续，不必守着页面等待",
    previewTitle: "快速演示 · 跳投复盘", previewStatus: "已完成", previewSummary: "训练概览", previewActions: "动作时间线",
    previewModelAlt: "实际模型输出：四机位篮球画面、人物骨架、球框与跳投阶段标注", previewPoseAlt: "真实模型处理画面：跳投出手时的人物骨架与篮球、篮筐检测", previewPoseCaption: "跳投 · 出手阶段", previewMixedAlt: "混合动作示例的实际四机位模型处理画面",
    previewAttempts: "出手", previewMakes: "命中", previewPeople: "参与者",
    capabilitiesEyebrow: "从录像到判断", capabilitiesTitle: "每个结论，都能回到画面",
    capabilityOneTitle: "多路证据，同步复盘", capabilityOneBody: "四个机位与注册视频形成同一条训练时间线，快速定位值得重看的片段",
    capabilityTwoTitle: "动作与投篮，分别求证", capabilityTwoBody: "动作识别与球轨结果独立呈现，避免为了整齐而强行匹配不确定证据",
    capabilityThreeTitle: "后台排队，回来继续", capabilityThreeBody: "GPU 任务串行处理，关掉页面也不会打断，晚些时候仍可接着查看结果",
    examplesEyebrow: "公开示例", examplesTitle: "先看看一份真实的复盘结构", examplesBody: "从原始画面到动作阶段，查看真实训练的分析结果",
    quickTitle: "快速演示", quickBody: "用更短处理路径预览动作数量、投篮汇总与复核画面", mixedTitle: "混合动作",
    mixedBody: "同一次训练，复盘 15 次三威胁与 12 次跳投", quickTag: "QUICK", mixedTag: "FULL", viewExample: "查看示例",
    ctaTitle: "把下一次训练，留成可回看的证据", ctaBody: "上传完成即可离开，大山冰会在后台排队，等你回来继续复盘", ctaAction: "开始复盘",
    footerLine: "大山冰 · 多机位篮球训练复盘", footerNote: "AI 结果用于训练辅助判断，请结合原始画面复核",
    authLoginTitle: "登录大山冰", authLoginBody: "继续查看你的训练任务、排队进度与复盘结果。",
    authRegisterTitle: "创建大山冰账号", authRegisterBody: "注册后即可提交训练视频，并在任意时间回来继续。",
    identity: "用户名或邮箱", username: "用户名", email: "邮箱", password: "密码", identityPlaceholder: "coach 或 coach@example.com",
    usernamePlaceholder: "3–50 个字符", emailPlaceholder: "coach@example.com", passwordPlaceholder: "至少 8 个字符",
    submitLogin: "登录", submitRegister: "创建账号", submittingLogin: "正在登录…", submittingRegister: "正在创建…",
    noAccount: "还没有账号？", hasAccount: "已经有账号？", goRegister: "立即注册", goLogin: "返回登录",
    identityRequired: "请输入用户名或邮箱", usernameShort: "用户名至少需要 3 个字符", emailInvalid: "请输入有效的邮箱地址",
    passwordShort: "密码至少需要 8 个字符", invalidCredentials: "用户名、邮箱或密码不正确", duplicateIdentity: "该用户名或邮箱已被注册",
    usernameRequired: "请输入用户名", usernameLong: "用户名不能超过 50 个字符", emailRequired: "请输入邮箱", emailLong: "邮箱不能超过 255 个字符",
    passwordRequired: "请输入密码", passwordLong: "密码不能超过 128 个字符", requestFailed: "暂时无法完成请求，请稍后重试",
    authChecking: "正在确认登录状态", authCheckFailed: "暂时无法确认登录状态", authCheckFailedBody: "网络或服务出现问题。请重试，我们不会把这次错误当作退出登录。", retry: "重试",
  },
  en: {
    logout: "Log out", loggingOut: "Logging out", logoutFailed: "Could not log out, please try again",
    menuOpen: "Open navigation menu", menuClose: "Close navigation menu",
    home: "Home", api: "API", github: "GitHub", onlineUse: "Online Use", login: "Log in", register: "Sign up", account: "Account",
    mainNav: "Main navigation", brandHome: "DaShanBing home", brandMark: "DaShanBing logo", brandPrimary: "DaShanBing", brandSecondary: "大山冰",
    metaTitle: "DaShanBing · Multi-camera basketball review", metaDescription: "DaShanBing turns multi-camera basketball training video into reviewable action and shooting insight",
    themeLight: "Switch to light theme", themeDark: "Switch to dark theme", language: "中文",
    heroEyebrow: "Multi-camera basketball review", heroTitle: "Turn multi-angle training video into basketball insight you can review",
    heroBody: "Submit five training videos, then return later to review every action and shot",
    heroPrimary: "Start a review", heroSecondary: "Explore demos", queueLabel: "Background queue", queueTitle: "Submit, then step away",
    queueBody: "Your task state is saved, Return to the same progress later instead of watching a page process",
    previewTitle: "Quick demo · Jump shots", previewStatus: "Completed", previewSummary: "Session overview", previewActions: "Action timeline",
    previewModelAlt: "Actual model output: four basketball camera views, pose skeletons, ball boxes and shot phases", previewPoseAlt: "Actual shot-release output with pose, basketball and hoop detections", previewPoseCaption: "Jump shot · Release", previewMixedAlt: "Actual four-camera model output from the mixed-actions example",
    previewAttempts: "Attempts", previewMakes: "Makes", previewPeople: "Players",
    capabilitiesEyebrow: "From footage to judgment", capabilitiesTitle: "Every conclusion leads back to video",
    capabilityOneTitle: "Synchronized evidence", capabilityOneBody: "Four camera angles and enrollment video form one training timeline, making key moments easy to revisit",
    capabilityTwoTitle: "Actions and shots, evaluated honestly", capabilityTwoBody: "Action recognition and ball tracking stay independent instead of forcing uncertain evidence to match",
    capabilityThreeTitle: "Queue it and come back", capabilityThreeBody: "GPU tasks run one at a time, Closing the page does not interrupt them, so you can return later",
    examplesEyebrow: "Public examples", examplesTitle: "See what a review looks like first", examplesBody: "See real training footage alongside its detected actions and phases",
    quickTitle: "Quick demo", quickBody: "Preview action counts, shot summaries, and review video through a shorter processing path", mixedTitle: "Mixed actions",
    mixedBody: "Review 15 triple-threat actions and 12 jump shots from one session", quickTag: "QUICK", mixedTag: "FULL", viewExample: "View example",
    ctaTitle: "Make your next session reviewable", ctaBody: "Leave after upload, DaShanBing queues the work in the background and keeps it ready for your return", ctaAction: "Start now",
    footerLine: "DaShanBing · Multi-camera basketball review", footerNote: "AI output supports coaching judgment, always verify against the source video",
    authLoginTitle: "Log in to DaShanBing", authLoginBody: "Continue to your training tasks, queue progress, and review results.",
    authRegisterTitle: "Create a DaShanBing account", authRegisterBody: "Submit training video, then return whenever the review is ready.",
    identity: "Username or email", username: "Username", email: "Email", password: "Password", identityPlaceholder: "coach or coach@example.com",
    usernamePlaceholder: "3–50 characters", emailPlaceholder: "coach@example.com", passwordPlaceholder: "At least 8 characters",
    submitLogin: "Log in", submitRegister: "Create account", submittingLogin: "Logging in…", submittingRegister: "Creating account…",
    noAccount: "New to DaShanBing?", hasAccount: "Already have an account?", goRegister: "Create one", goLogin: "Back to login",
    identityRequired: "Enter your username or email", usernameShort: "Username must be at least 3 characters", emailInvalid: "Enter a valid email address",
    passwordShort: "Password must be at least 8 characters", invalidCredentials: "The username, email, or password is incorrect",
    duplicateIdentity: "That username or email is already registered", usernameRequired: "Enter a username", usernameLong: "Username cannot exceed 50 characters",
    emailRequired: "Enter an email address", emailLong: "Email cannot exceed 255 characters", passwordRequired: "Enter a password", passwordLong: "Password cannot exceed 128 characters",
    requestFailed: "We could not complete the request. Try again shortly.", authChecking: "Checking your sign-in status",
    authCheckFailed: "We could not confirm your sign-in status", authCheckFailedBody: "There may be a network or service problem. Retry without being signed out.", retry: "Retry",
  },
} as const;

export type Locale = keyof typeof copy;
export type CopyKey = keyof (typeof copy)["zh"];
