import { useLocale } from "../providers/LocaleProvider";

const copy = {
  drafts: ["草稿数量", "Drafts"], unfinished: ["未完成任务", "Unfinished tasks"], daily_video: ["每日视频任务", "Daily video submissions"], daily_ai: ["每日 AI 请求", "Daily AI requests"], ai_concurrency: ["AI 并发数", "AI concurrency"], defaultQuotas: ["默认配额", "Default quotas"], quotaHelp: ["新请求使用更新后的上限，现有运行任务不受中断", "Updated limits apply to new requests; current work continues."], overrideHelp: ["留空以使用默认配额，0 表示不允许新请求", "Leave blank to use the default. Zero blocks new requests."], usage: ["用量 / 上限", "Usage / limit"],
  video_enabled: ["视频任务准入", "Video admission"], video_paused: ["暂停视频队列", "Pause video queue"], ai_enabled: ["AI 任务准入", "AI admission"], ai_paused: ["暂停 AI 队列", "Pause AI queue"], schedulingSettings: ["队列控制", "Queue controls"], admissionHelp: ["准入控制影响新提交，暂停控制影响新任务领取，已运行任务继续执行", "Admission controls new submissions. Pausing controls new claims. Running jobs continue."],
  kind: ["任务类型", "Job kind"], video: ["视频", "Video"], ai: ["AI", "AI"], preset: ["预设", "Preset"], select: ["选择", "Select"], hold: ["暂缓", "Hold"], release: ["恢复排队", "Release"], priority: ["优先级", "Priority"], backfill: ["补全预期版本", "Backfill expected version"], holdSelected: ["暂缓所选", "Hold selected"], releaseSelected: ["恢复所选", "Release selected"], prioritySelected: ["调整所选优先级", "Set selected priority"], retrySelected: ["重试所选", "Retry selected"], backfillSelected: ["补全所选", "Backfill selected"], held: ["已暂缓", "Held"], attempts: ["尝试次数", "Attempts"], adminRetries: ["管理重试次数", "Administrator retries"], interrupted: ["已中断", "Interrupted"], yes: ["是", "Yes"], no: ["否", "No"],
  repairBudget: ["今日修复预算 (UTC)", "Repair budget today (UTC)"], repairHelp: ["重试与补全仅适用于服务允许的失败任务，不覆盖成功结果", "Retry and backfill apply only to eligible failed jobs and preserve successful output."], version: ["应用版本", "Application version"], databaseRevision: ["数据库版本", "Database revision"], videoWorker: ["视频工作进程", "Video worker"], aiWorker: ["AI 工作进程", "AI worker"], backupStatus: ["备份状态", "Backup status"], enabled: ["已启用", "Enabled"], disabled: ["已禁用", "Disabled"], resourceUsage: ["资源状态", "Resources"], cpuCores: ["CPU 逻辑核心", "CPU logical cores"], cpuUsage: ["CPU 使用率", "CPU utilization"], cpuLoad: ["系统平均负载", "Load average"], memory: ["内存可用 / 总量", "Memory available / total"], disk: ["磁盘空闲 / 总量", "Disk free / total"], gpu: ["GPU 使用率", "GPU utilization"], gpuMemory: ["GPU 显存已用 / 总量", "GPU memory used / total"], activeUsers: ["启用用户 / 全部", "Active users / total"], videoSubmissions: ["今日视频提交", "Video submissions today"], aiAttempts: ["今日 AI 实际请求", "Actual AI requests today"], aiTokens: ["今日 AI 令牌用量", "AI tokens today"], queues: ["队列概况", "Queue summary"], actor: ["操作人 ID", "Actor ID"], action: ["操作", "Action"], targets: ["对象", "Targets"], changes: ["变更", "Changes"], revokedHelp: ["将撤销该用户的全部会话和 API 密钥", "This revokes all sessions and API keys for this user."], disableHelp: ["停用账户将撤销该用户的会话和 API 密钥", "Disabling this account revokes its sessions and API keys."],
  timingScope: ["今日成功完成任务（UTC），AI 总耗时包含排队与重试", "Successful completions today (UTC). AI total includes queueing and retries."], errorScope: ["当前失败积压，涵盖全部日期", "Current failed backlog across all dates."], engineFailed: ["执行引擎失败", "Engine failure"], registrationCountMismatch: ["注册人数不匹配", "Registration count mismatch"], registrationQualityFailed: ["注册质量不足", "Registration quality failed"], registrationConfigRequired: ["缺少注册配置", "Registration configuration required"], preparationFailed: ["准备阶段失败", "Preparation failed"], generationFailed: ["生成失败", "Generation failed"],
  timingSummary: ["耗时概况（秒）", "Timing summary (seconds)"], videoQueueTime: ["视频排队", "Video queue"], videoExecutionTime: ["视频执行", "Video execution"], aiTotalTime: ["AI 总耗时", "AI total"], sampleCount: ["样本数", "Samples"], errorCategories: ["错误分类", "Error categories"], errorCode: ["分类", "Category"], errorCount: ["数量", "Count"], telemetryUnavailable: ["暂无数据", "Unavailable"], noRecordedErrors: ["暂无已记录错误", "No recorded errors"],
  administration: ["管理控制台", "Administration"], navigation: ["管理员导航", "Administrator navigation"],
  overview: ["概览", "Overview"], users: ["用户管理", "Users"], scheduling: ["任务调度", "Scheduling"], quotas: ["配额与并发", "Quotas & concurrency"], operations: ["运行状态", "Operations state"], audit: ["审计日志", "Audit log"],
  overviewBody: ["服务用量与调度概况", "Service usage and scheduling at a glance."], usersBody: ["管理账户状态、会话与使用额度", "Manage account status, sessions and usage limits."], schedulingBody: ["查看任务元数据并管理队列", "Inspect task metadata and manage the queue."], quotasBody: ["设置使用额度与并发上限", "Configure usage allowances and concurrency limits."], operationsBody: ["只读服务状态与容量信息", "Read-only service health and capacity."], auditBody: ["追踪管理操作及其原因", "Trace administrative changes and their reasons."],
  budgetExhausted: ["今日修复预算已用尽，请等待 UTC 日期更新", "The daily repair budget is exhausted. Wait for the next UTC day."], invalidValues: ["输入超出服务限制，请检查后重试", "Check the input values against the service limits."],
  loading: ["正在加载", "Loading"], loadFailed: ["无法加载数据", "Unable to load data"], requestFailed: ["操作未完成，请刷新状态后重试", "The action did not complete. Refresh the state before trying again."], forbidden: ["权限已变更，请重新登录", "Access has changed. Please sign in again."], conflict: ["状态已变更，请刷新后重新确认", "The state changed. Refresh and confirm again."], unavailable: ["服务暂时不可用，请稍后重试", "The service is unavailable. Please try again later."],
  retry: ["重试", "Retry"], refresh: ["刷新", "Refresh"], empty: ["暂无记录", "No records"], emptyBody: ["当前范围没有可显示的记录", "There are no records in this scope."], clearFilters: ["清除筛选", "Clear filters"], search: ["搜索", "Search"], filter: ["筛选", "Filter"], all: ["全部", "All"], apply: ["应用", "Apply"], status: ["状态", "Status"], role: ["角色", "Role"], administrator: ["管理员", "Administrator"], ordinary: ["普通用户", "User"], active: ["启用", "Active"], inactive: ["停用", "Inactive"],
  username: ["用户名", "Username"], userId: ["用户 ID", "User ID"], email: ["邮箱", "Email"], created: ["创建时间", "Created"], updated: ["更新时间", "Updated"], actions: ["操作", "Actions"], details: ["元数据", "Metadata"], close: ["关闭", "Close"], cancel: ["取消", "Cancel"], confirm: ["确认操作", "Confirm action"], reason: ["操作原因", "Reason"], reasonHint: ["请填写 3–500 字的原因，该原因将记录到审计日志", "Enter a reason of 3–500 characters for the audit log."], acknowledge: ["我已核对所选对象与变更", "I have reviewed the selected targets and changes."], saved: ["操作已完成", "Action completed"], working: ["正在执行", "Working"], batchHint: ["每次最多选择 10 项", "Select up to 10 items"], selected: ["已选", "Selected"],
  disable: ["停用账户", "Disable account"], enable: ["启用账户", "Enable account"], revoke: ["撤销会话", "Revoke sessions"], editQuota: ["编辑配额", "Edit quota"], save: ["保存变更", "Save changes"], cancelTask: ["取消任务", "Cancel task"], retryTask: ["重试任务", "Retry task"], requeue: ["重新入队", "Requeue"],
  previous: ["上一页", "Previous page"], next: ["下一页", "Next page"], page: ["页", "Page"], total: ["共", "Total"], rows: ["每页条数", "Rows per page"],
  taskId: ["任务 ID", "Task ID"], owner: ["所属用户", "Owner"], progress: ["进度", "Progress"], queued: ["排队中", "Queued"], running: ["运行中", "Running"], failed: ["失败", "Failed"], completed: ["已完成", "Completed"], canceled: ["已取消", "Canceled"], expired: ["已过期", "Expired"], draft: ["草稿", "Draft"], uploading: ["上传中", "Uploading"],
  collapse: ["收起侧边栏", "Collapse sidebar"], expand: ["展开侧边栏", "Expand sidebar"], menuOpen: ["打开管理菜单", "Open administrator menu"], menuClose: ["关闭管理菜单", "Close administrator menu"], readOnly: ["只读", "Read only"], unknown: ["未知", "Unknown"], unlimited: ["不限", "Unlimited"], inherited: ["使用默认值", "Use default"],
} as const;
export type AdminCopyKey = keyof typeof copy;
export function useAdminCopy() { const { locale } = useLocale(); return (key: AdminCopyKey) => copy[key][locale === "zh" ? 0 : 1]; }
